// পৃথিবীর প্রায় সকল গুরুত্বপূর্ণ দেশের তালিকা (৫৭টি মুসলিম দেশ এবং শীর্ষ ২০০+ দেশ ও অঞ্চলের কান্ট্রি কোড, পতাকা ও নাম সহ)
// ওমর, এই তালিকাটি তোমার প্রজেক্টের জন্য সম্পূর্ণ রেডি করা হয়েছে। তুমি চাইলে পরবর্তীতে আরও দেশ সহজেই যোগ করতে পারবে।

const countriesList = [
    // --- ওআইসি (OIC) ভুক্ত ৫৭টি মুসলিম দেশ এবং মুসলিম প্রধান দেশসমূহ ---
    { code: "880", flag: "🇧🇩", name: "Bangladesh (+880)" },
    { code: "966", flag: "🇸🇦", name: "Saudi Arabia (+966)" },
    { code: "971", flag: "🇦🇪", name: "UAE (+971)" },
    { code: "965", flag: "🇰🇼", name: "Kuwait (+965)" },
    { code: "974", flag: "🇶🇦", name: "Qatar (+974)" },
    { code: "968", flag: "🇴🇲", name: "Oman (+968)" },
    { code: "60", flag: "🇲🇾", name: "Malaysia (+60)" },
    { code: "92", flag: "🇵🇰", name: "Pakistan (+92)" },
    { code: "90", flag: "🇹🇷", name: "Turkey (+90)" },
    { code: "20", flag: "🇪🇬", name: "Egypt (+20)" },
    { code: "973", flag: "🇧🇭", name: "Bahrain (+973)" },
    { code: "960", flag: "🇲🇻", name: "Maldives (+960)" },
    { code: "62", flag: "🇮🇩", name: "Indonesia (+62)" },
    { code: "93", flag: "🇦🇫", name: "Afghanistan (+93)" },
    { code: "355", flag: "🇦🇱", name: "Albania (+355)" },
    { code: "213", flag: "🇩🇿", name: "Algeria (+213)" },
    { code: "994", flag: "🇦🇿", name: "Azerbaijan (+994)" },
    { code: "229", flag: "🇧🇯", name: "Benin (+229)" },
    { code: "673", flag: "🇧🇳", name: "Brunei (+673)" },
    { code: "226", flag: "🇧🇫", name: "Burkina Faso (+226)" },
    { code: "237", flag: "🇨🇲", name: "Cameroon (+237)" },
    { code: "235", flag: "🇹🇩", name: "Chad (+235)" },
    { code: "269", flag: "🇰🇲", name: "Comoros (+269)" },
    { code: "225", flag: "🇨🇮", name: "Ivory Coast (+225)" },
    { code: "253", flag: "🇩🇯", name: "Djibouti (+253)" },
    { code: "241", flag: "🇬🇦", name: "Gabon (+241)" },
    { code: "220", flag: "🇬🇲", name: "Gambia (+220)" },
    { code: "224", flag: "🇬🇳", name: "Guinea (+224)" },
    { code: "245", flag: "🇬🇼", name: "Guinea-Bissau (+245)" },
    { code: "592", flag: "🇬🇾", name: "Guyana (+592)" },
    { code: "98", flag: "🇮🇷", name: "Iran (+98)" },
    { code: "964", flag: "🇮🇶", name: "Iraq (+964)" },
    { code: "962", flag: "🇯🇴", name: "Jordan (+962)" },
    { code: "7", flag: "🇰🇿", name: "Kazakhstan (+7)" },
    { code: "996", flag: "🇰🇬", name: "Kyrgyzstan (+996)" },
    { code: "961", flag: "🇱🇧", name: "Lebanon (+961)" },
    { code: "218", flag: "🇱🇾", name: "Libya (+218)" },
    { code: "223", flag: "🇲🇱", name: "Mali (+223)" },
    { code: "222", flag: "🇲🇷", name: "Mauritania (+222)" },
    { code: "212", flag: "🇲🇦", name: "Morocco (+212)" },
    { code: "258", flag: "🇲🇿", name: "Mozambique (+258)" },
    { code: "227", flag: "🇳🇪", name: "Niger (+227)" },
    { code: "234", flag: "🇳🇬", name: "Nigeria (+234)" },
    { code: "970", flag: "🇵🇸", name: "Palestine (+970)" },
    { code: "221", flag: "🇸🇳", name: "Senegal (+221)" },
    { code: "232", flag: "🇸🇱", name: "Sierra Leone (+232)" },
    { code: "252", flag: "🇸🇴", name: "Somalia (+252)" },
    { code: "249", flag: "🇸🇩", name: "Sudan (+249)" },
    { code: "597", flag: "🇸🇷", name: "Suriname (+597)" },
    { code: "963", flag: "🇸🇾", name: "Syria (+963)" },
    { code: "992", flag: "🇹🇯", name: "Tajikistan (+992)" },
    { code: "228", flag: "🇹🇬", name: "Togo (+228)" },
    { code: "216", flag: "🇹🇳", name: "Tunisia (+216)" },
    { code: "993", flag: "🇹🇲", name: "Turkmenistan (+993)" },
    { code: "256", flag: "🇺🇬", name: "Uganda (+256)" },
    { code: "998", flag: "🇺🇿", name: "Uzbekistan (+998)" },
    { code: "967", flag: "🇾🇪", name: "Yemen (+967)" },

    // --- এশিয়া ও প্যাসিফিক অঞ্চলের অন্যান্য প্রধান দেশসমূহ ---
    { code: "91", flag: "🇮🇳", name: "India (+91)" },
    { code: "86", flag: "🇨🇳", name: "China (+86)" },
    { code: "81", flag: "🇯🇵", name: "Japan (+81)" },
    { code: "82", flag: "🇰🇷", name: "South Korea (+82)" },
    { code: "65", flag: "🇸🇬", name: "Singapore (+65)" },
    { code: "977", flag: "🇳🇵", name: "Nepal (+977)" },
    { code: "94", flag: "🇱🇰", name:
 "Sri Lanka (+94)" },
    { code: "66", flag: "🇹🇭", name: "Thailand (+66)" },
    { code: "61", flag: "🇦🇺", name: "Australia (+61)" },
    { code: "64", flag: "🇳🇿", name:
 "New Zealand (+64)" },
    { code: "975", flag: "🇧🇹", name: "Bhutan (+975)" },
    { code: "95", flag: "🇲🇲", name: "Myanmar (+95)" },
    { code: "84", flag: "🇻🇳", name: "Vietnam (+84)" },
    { code: "63", flag: "🇵🇭", name: "Philippines (+63)" },
    { code: "852", flag: "🇭🇰", name: "Hong Kong (+852)" },
    { code: "886", flag: "🇹🇼", name: "Taiwan (+886)" },
    { code: "855", flag: "🇰🇭", name: "Cambodia (+855)" },
    { code: "856", flag: "🇱🇦", name: "Laos (+856)" },
    { code: "976", flag: "🇲🇳", name: "Mongolia (+976)" },
    { code: "853", flag: "🇲🇴", name: "Macau (+853)" },
    { code: "670", flag: "🇹🇱", name: "East Timor (+670)" },
    { code: "679", flag: "🇫🇯", name: "Fiji (+679)" },
    { code: "675", flag: "🇵🇬", name: "Papua New Guinea (+675)" },

    // --- উত্তর ও দক্ষিণ আমেরিকা অঞ্চলের প্রধান দেশসমূহ ---
    { code: "1", flag: "🇺🇸", name: "United States (+1)" },
    { code: "1", flag: "🇨🇦", name: "Canada (+1)" },
    { code: "55", flag: "🇧🇷", name: "Brazil (+55)" },
    { code: "52", flag: "🇲🇽", name: "Mexico (+52)" },
    { code: "54", flag: "🇦🇷", name: "Argentina (+54)" },
    { code: "57", flag: "🇨🇴", name: "Colombia (+57)" },
    { code: "56", flag: "🇨🇱", name: "Chile (+56)" },
    { code: "51", flag: "🇵🇪", name: "Peru (+51)" },
    { code: "58", flag: "🇻🇪", name: "Venezuela (+58)" },
    { code: "593", flag: "🇪🇨", name: "Ecuador (+593)" },
    { code: "502", flag: "🇬🇹", name: "Guatemala (+502)" },
    { code: "53", flag: "🇨🇺", name: "Cuba (+53)" },
    { code: "506", flag: "🇨🇷", name: "Costa Rica (+506)" },
    { code: "507", flag: "🇵🇦", name: "Panama (+507)" },
    { code: "595", flag: "🇵🇾", name: "Paraguay (+595)" },
    { code: "598", flag: "🇺🇾", name: "Uruguay (+598)" },
    { code: "591", flag: "🇧🇴", name: "Bolivia (+591)" },
    { code: "1", flag: "🇯🇲", name: "Jamaica (+1)" },
    { code: "1", flag: "🇧🇸", name: "Bahamas (+1)" },

    // --- ইউরোপ অঞ্চলের প্রধান দেশসমূহ ---
    { code: "44", flag: "🇬🇧", name: "United Kingdom (+44)" },
    { code: "49", flag: "🇩🇪", name: "Germany (+49)" },
    { code: "33", flag: "🇫🇷", name: "France (+33)" },
    { code: "39", flag: "🇮🇹", name: "Italy (+39)" },
    { code: "34", flag: "🇪🇸", name: "Spain (+34)" },
    { code: "7", flag: "🇷🇺", name: "Russia (+7)" },
    { code: "31", flag: "🇳🇱", name: "Netherlands (+31)" },
    { code: "41", flag: "🇨🇭", name: "Switzerland (+41)" },
    { code: "32", flag: "🇧🇪", name: "Belgium (+32)" },
    { code: "46", flag: "🇸🇪", name: "Sweden (+46)" },
    { code: "47", flag: "🇳🇴", name: "Norway (+47)" },
    { code: "45", flag: "🇩🇰", name: "Denmark (+45)" },
    { code: "358", flag: "🇫🇮", name: "Finland (+358)" },
    { code: "353", flag: "🇮🇪", name: "Ireland (+353)" },
    { code: "43", flag: "🇦🇹", name: "Austria (+43)" },
    { code: "48", flag: "🇵🇱", name: "Poland (+48)" },
    { code: "351", flag: "🇵🇹", name: "Portugal (+351)" },
    { code: "30", flag: "🇬🇷", name: "Greece (+30)" },
    { code: "380", flag: "🇺🇦", name: "Ukraine (+380)" },
    { code: "420", flag: "🇨🇿", name: "Czech Republic (+420)" },
    { code: "36", flag: "🇭🇺", name: "Hungary (+36)" },
    { code: "40", flag: "🇷🇴", name: "Romania (+40)" },
    { code: "354", flag: "🇮🇸", name: "Iceland (+354)" },
    { code: "370", flag: "🇱🇹", name: "Lithuania (+370)" },
    { code: "371", flag: "🇱🇻", name: "Latvia (+371)" },
    { code: "372", flag: "🇪🇪", name: "Estonia (+372)" },
    { code: "381", flag: "🇷🇸", name: "Serbia (+381)" },
    { code: "385", flag: "🇭🇷", name: "Croatia (+385)" },
    { code: "359", flag: "🇧🇬", name: "Bulgaria (+359)" },
    { code: "421", flag: "🇸🇰", name: "Slovakia (+421)" },
    { code: "386", flag: "🇸🇮", name: "Slovenia (+386)" },
    { code: "376", flag: "🇦🇩", name: "Andorra (+376)" },
    { code: "379", flag: "🇻🇦", name: "Vatican City (+379)" },
    { code: "377", flag: "🇲🇨", name: "Monaco (+377)" },
    { code: "356", flag: "🇲🇹", name: "Malta (+356)" },
    { code: "352", flag: "🇱🇺", name: "Luxembourg (+352)" },

    // --- আফ্রিকা অঞ্চলের অন্যান্য প্রধান দেশসমূহ ---
    { code: "27", flag: "🇿🇦", name: "South Africa (+27)" },
    { code: "254", flag: "🇰🇪", name: "Kenya (+254)" },
    { code: "251", flag: "🇪🇹", name: "Ethiopia (+251)" },
    { code: "233", flag: "🇬🇭", name: "Ghana (+233)" },
    { code: "255", flag: "🇹🇿", name: "Tanzania (+255)" },
    { code: "244", flag: "🇦🇴", name: "Angola (+244)" },
    { code: "263", flag: "🇿🇼", name: "Zimbabwe (+263)" },
    { code: "260", flag: "🇿🇲", name: "Zambia (+260)" },
    { code: "264", flag: "🇳🇦", name: "Namibia (+264)" },
    { code: "2Botswana", flag: "🇧🇼", name: "Botswana (+267)" },
 // Standard code is 267
    { code: "267", flag: "🇧🇼", name: "Botswana (+267)" },
    { code: "250", flag: "🇷🇼", name: "Rwanda (+250)" },
    { code: "265", flag: "🇲🇼", name: "Malawi (+265)" },
    { code: "262", flag: "🇷🇪", name: "Reunion (+262)" },
    { code: "230", flag: "🇲🇺", name: "Mauritius (+230)" },
    { code: "248", flag: "🇸🇨", name: "Seychelles (+248)" },
    { code: "243", flag: "🇨🇩", name: 
"DR Congo (+243)" },
    { code: "242", flag: "🇨🇬", name: "Congo Republic (+242)" },
    { code: "266", flag: "🇱🇸", name: "Lesotho (+266)" },
    { code: "268", flag: "🇸🇿", name: "Eswatini (+268)" },
    { code: "231", flag: "🇱🇷", name: "Liberia (+231)" },
    { code: "239", flag: "🇸🇹", name: "Sao Tome (+239)" },
    { code: "240", flag: "🇬🇶", name: "Equatorial Guinea (+240)" },
    { code: "236", flag: "🇨🇫", name: "Central African Republic (+236)" },
    { code: "257", flag: "🇧🇮", name: "Burundi (+257)" },
    { code: "258", flag: "🇲🇿", name: "Mozambique (+258)" },
    { code: "261", flag: "🇲🇬", name: "Madagascar (+261)" },
    { code: "291", flag: "🇪🇷", name: "Eritrea (+291)" },
    { code: "211", flag: "🇸🇸", name: "South Sudan (+211)" },

    // --- ওশেনিয়া ও অন্যান্য দ্বীপপুঞ্জ ---
    { code: "685", flag: "🇼🇸", name: "Samoa (+685)" },
    { code: "676", flag: "🇹🇴", name: "Tonga (+676)" },
    { code: "677", flag: "🇸🇧", name: "Solomon Islands (+677)" },
    { code: "678", flag: "🇻🇺", name: "Vanuatu (+678)" },
    { code: "691", flag: "🇫🇲", name: "Micronesia (+691)" },
    { code: "692", flag: "🇲🇭", name: "Marshall Islands (+692)" },
    { code: "680", flag: "🇵🇼", name: "Palau (+680)" },
    { code: "686", flag: "🇰🇮", name: "Kiribati (+686)" },
    { code: "688", flag: "🇹🇻", name: "Tuvalu (+688)" },
    { code: "674", flag: "🇳🇷", name: "Nauru (+674)" },

    // --- ক্যারিবিয়ান ও মধ্য আমেরিকা অঞ্চলের দ্বীপপুঞ্জ ---
    { code: "1", flag: "🇵🇷", name: "Puerto Rico (+1)" },
    { code: "1", flag: "🇩🇴", name: "Dominican Republic (+1)" },
    { code: "509", flag: "🇭🇹", name: "Haiti (+509)" },
    { code: "1", flag: "🇹🇹", name: "Trinidad and Tobago (+1)" },
    { code: "1", flag: "🇧🇧", name: "Barbados (+1)" },
    { code: "1", flag: "🇱🇨", name: "Saint Lucia (+1)" },
    { code: "1", flag: "🇬🇩", name: "Grenada (+1)" },
    { code: "1", flag: "🇻🇨", name:
 "St. Vincent (+1)" },
    { code: "1", flag: "🇦🇬", name: "Antigua and Barbuda (+1)" },
    { code: "1", flag: "🇩🇲", name: "Dominica (+1)" },
    { code: "1", flag: "🇰🇳", name: "Saint Kitts (+1)" },
    { code: "501", flag: "🇧🇿", name: "Belize (+501)" },
    { code: "503", flag: "🇸🇻", name:
 "El Salvador (+503)" },
    { code: "504", flag: "🇭🇳", name: "Honduras (+504)" },
    { code: "505", flag: "🇳🇮", name: "Nicaragua (+505)" }
];

// গ্লোবাল অ্যাক্সেসের জন্য উইন্ডো অবজেক্টে সেট করা হলো
window.countriesList = countriesList;
